# Generated by Django 4.2.6 on 2023-10-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_customuser_role'),
        ('homepage', '0003_customuser_address_customuser_birthdate_and_more'),
    ]

    operations = [
    ]
