# Generated by Django 4.2.6 on 2023-10-25 18:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20231024_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn10',
            field=models.TextField(blank=True, null=True),
        ),
    ]
