# Generated by Django 4.2.6 on 2023-10-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_bookmark_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='title',
        ),
    ]
