# Generated by Django 4.2.6 on 2023-10-25 19:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookdonation', '0003_item_delete_data_donasi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='data_donasi1',
        ),
    ]
