# Generated by Django 4.2.6 on 2023-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdonation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_donasi',
            name='resi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_donasi',
            name='total_buku',
            field=models.IntegerField(),
        ),
    ]
