# Generated by Django 4.2.6 on 2023-10-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdonation', '0005_rename_name_data_donasi1_nama_pengirim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_donasi1',
            old_name='total_buku',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='data_donasi1',
            old_name='resi',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='data_donasi1',
            old_name='nama_pengirim',
            new_name='name',
        ),
    ]
