# Generated by Django 4.2.6 on 2023-10-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdonation', '0006_rename_total_buku_data_donasi1_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_donasi1',
            old_name='name',
            new_name='nama_pengirim',
        ),
    ]
