# Generated by Django 4.2.6 on 2023-10-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdonation', '0007_rename_name_data_donasi1_nama_pengirim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_donasi1',
            old_name='amount',
            new_name='total_buku',
        ),
    ]
