# Generated by Django 4.2.6 on 2023-10-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookdonation', '0009_rename_description_data_donasi1_resi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_donasi1',
            old_name='nama_pengirim',
            new_name='judul_buku',
        ),
    ]
