# Generated by Django 4.2.6 on 2023-10-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdonation', '0010_rename_nama_pengirim_data_donasi1_judul_buku'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_donasi1',
            name='status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
